// <auto-generated />

namespace Demo.API.Data.Migrations
{
    using System;

    using Demo.API.Data.DatabaseContext;

    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Metadata;

    [DbContext(typeof(DemoContext))]
    internal class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128).HasAnnotation(
                    "SqlServer:ValueGenerationStrategy",
                    SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity(
                "Demo.API.Data.Models.Catalog",
                b =>
                    {
                        b.Property<Guid>("Id").ValueGeneratedOnAdd();

                        b.Property<DateTime>("CreatedDate");

                        b.Property<bool>("Disabled").ValueGeneratedOnAdd().HasDefaultValue(false);

                        b.Property<DateTime>("ModifiedDate");

                        b.Property<string>("Name").IsRequired().HasMaxLength(100);

                        b.Property<int>("Order");

                        b.HasKey("Id");

                        b.ToTable("Catalogs");
                    });

            modelBuilder.Entity(
                "Demo.API.Data.Models.Product",
                b =>
                    {
                        b.Property<Guid>("Id").ValueGeneratedOnAdd();

                        b.Property<Guid>("CatalogId");

                        b.Property<DateTime>("CreatedDate");

                        b.Property<bool>("Disabled");

                        b.Property<DateTime>("ModifiedDate");

                        b.Property<string>("Name").IsRequired().HasMaxLength(100);

                        b.Property<int>("Order");

                        b.HasKey("Id");

                        b.ToTable("Products");
                    });
#pragma warning restore 612, 618
        }
    }
}